stages:
   - build
   - test
   - deploy

test: 
   stage: test
   before_script:
      - pwd
      - ls
   script:
#      - gradle test
      - (cd frontend/car-rental-app && \
         docker build -t frontendtest . && \
         docker run -d frontendtest && \
         docker exec -d frontendtest npm test && \
         docker rm frontendtest -f
         )
      - (cd backend && \
         docker build -t backendtest . && \
         docker run -d backendtest && \
         docker exec -d backendtest gradle test && \
         docker rm backendtest -f
         )
      - echo "Success"
   tags:
      - test

build_develop:
   stage: build
   script:
      - docker-compose build
   tags:
      - build

deploy_develop:
   stage: deploy
   script:
      - docker-compose down
      - docker-compose up -d
   tags: 
      - deploy