stages:
   - build
   - test
   - deploy

test: 
   stage: test
   before_script:
      - pwd
      - ls
   script:
#      - gradle test
      - cd frontend/car-rental-app
      - docker build -t frontendtest .
      - docker run -d --name fronttest frontendtest 
      - docker exec -d fronttest npm test 
      - docker rm fronttest -f
      
      - cd ..
      - cd ..

      - cd backend
      - docker build -t backendtest .
      - docker run -d --name backtest backendtest
      - docker exec -d backtest gradle test 
      - docker rm backtest -f 

      - cd ..
      - (pwd && ls)
      - echo "Success"
   tags:
      - test

build_develop:
   stage: build
   script:
      - docker-compose build
   tags:
      - build

deploy_develop:
   stage: deploy
   script:
      - docker-compose down
      - docker-compose up -d
   tags: 
      - deploy