stages:
   - build
   - test
   - deploy

test: 
   stage: test
   script:
      - gradle test
      - npm test
      - echo "Success"
   tags:
      - test

build_develop:
   stage: build
   script:
      - docker-compose build
   tags:
      - build

deploy_develop:
   stage: deploy
   script:
      - docker-compose down
      - docker-compose up -d
   tags: 
      - deploy