stages:
   - build
   - test
   - deploy

test: 
   stage: test
   script:
      - echo "Tests"
      - cd backend
      - docker run -d backend 
      - docker exec backend gradle test
      - docker rm backend -f 
      - cd ..
#     Frontend
      - cd frontend/car-rental-app/
      - docker run -d frontend 
      - docker exec frontend npm
      - docker rm frontend -f 
      - cd ..
      - cd ..
      - echo "Success"
   tags:
      - test

build_develop:
   stage: build
   script:
      - docker-compose build
   tags:
      - build

deploy_develop:
   stage: deploy
   script:
      - docker-compose down
      - docker-compose up -d
   tags: 
      - deploy