stages:
   - build
   - test
   - deploy

test: 
   stage: test
   before_script:
      - pwd
      - ls
   script:
#      - gradle test
      - cd frontend/car-rental-app
      - docker run -d frontend 
      - docker exec -d frontend npm test
      - docker rm frontend -f
      - echo "Success"
   tags:
      - test

build_develop:
   stage: build
   script:
      - docker-compose build
   tags:
      - build

deploy_develop:
   stage: deploy
   script:
      - docker-compose down
      - docker-compose up -d
   tags: 
      - deploy