stages:
   - build
   - test
   - deploy

test: 
   stage: test
   before_script:
      - pwd
      - ls
   script:
#      - gradle test
      - docker build -t frontendtest . /frontend/car-rental-app/
      - docker run -d frontendtest /frontend/car-rental-app/
      - docker exec -d frontendtest npm test /frontend/car-rental-app/
      - docker rm frontendtest -f /frontend/car-rental-app/
         
      - docker build -t backendtest . /backend/
      - docker run -d backendtest /backend/
      - docker exec -d backendtest gradle test /backend/
      - docker rm backendtest -f /backend/

      - echo "Success"
   tags:
      - test

build_develop:
   stage: build
   script:
      - docker-compose build
   tags:
      - build

deploy_develop:
   stage: deploy
   script:
      - docker-compose down
      - docker-compose up -d
   tags: 
      - deploy