stages:
   - test
   - build
   - deploy

test: 
    script:
        - echo "Here goes test"
#        - gradle test

build_develop:
   script:
      - docker-compose build

deploy_develop:
   script:
      - docker-compose down
      - docker-compose up -d
