stages:
   - build
   - test
   - deploy

test: 
   stage: test
   script:
      - echo "Here goes test"
      - docker exec -d carrentalbackend gradle test
      - echo "Backedn test ended"
#     Frontend      
      - docker exec -d carrentalfrontend npm test
      - echo "Success"
   tags:
      - test

build_develop:
   stage: build
   script:
      - docker-compose build
   tags:
      - build

deploy_develop:
   stage: deploy
   script:
      - docker-compose down
      - docker-compose up -d
   tags: 
      - deploy