
# ---- DEVELOP BRANCH ---- #

version: '3.3'
services:
# Data Base image
  postgresdb:
    container_name: car_rental_postgres_dev
    image: car_rental_postgres_dev
    build: ./postgres/
    #12.2
    expose: 
      - 5432
    environment:
      - POSTGRES_PASSWORD=polska525
      - POSTGRES_USER=postgres
      - POSTGRES_DB=car_rental
    volumes:
      - car_rental_postgres_dev:/var/lib/postgresql/data

# Backend Application image
  backend:
    image: car_rental_back_dev
    container_name: car_rental_back_dev
    build: ./backend
    depends_on:
      - postgresdb
    ports:
      - "30093:8080" 

# Frontend Application image
  frontend:
    image: car_rental_front_dev
    container_name: car_rental_front_dev
    build: ./frontend/car-rental-app/
    ports:
      - "30094:5000"

volumes:
  car_rental_postgres_dev: 
    