
# ---- DEVELOP BRANCH ---- #

version: '3.3'
services:
# Data Base image
  postgresdb:
    container_name: car_rent_postgres_dev
    image: car_rent_postgres_dev
    build: ./postgres/
    #12.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=polska525
      - POSTGRES_USER=postgres
      - POSTGRES_DB=car_rental
    volumes:
      - car_rent_postgres_dev:/var/lib/postgresql/data

# Backend Application image
  backend:
    image: car_rent_back_dev
    container_name: car_rent_back_dev
    build: ./backend
    depends_on:
      - postgresdb

# Frontend Application image
  frontend:
    image: car_rent_front_dev
    container_name: car_rent_front_dev
    build: ./frontend/car-rental-app/
    ports:
      - "30084:5000"

volumes:
  car_rent_postgres_dev: 
    