spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental
    username: postgres
    password: polska525
    initialization-mode: always
    data: classpath:/data.sql
server:
  port: 8080